
// No longer need Firebase Timestamp
// import type { Timestamp } from 'firebase/firestore'; 

export interface Investigation {
  id: string; // Supabase UUID
  title: string;
  description: string;
  assignedInvestigator: string;
  status: 'Aberta' | 'Em Andamento' | 'Concluída' | 'Arquivada';
  creationDate: string; // ISO string (from Supabase 'created_at')
  roNumber: string; // Gerado pela lógica do app
  occurrenceDate?: string; // ISO string
  mediaUrls?: string[]; // Array de URLs para imagens/vídeos do Supabase Storage
}

export interface InvestigationInput { // For form data before it's processed
  title: string;
  description: string;
  assignedInvestigator: string;
  status: 'Aberta' | 'Em Andamento' | 'Concluída' | 'Arquivada';
  // creationDate will be set by Supabase ('created_at')
  // roNumber will be generated by the service
  occurrenceDate?: string; // ISO string
  mediaUrls?: string[]; // Populated after file uploads
}
